name: Obituary Scraper Workflow

on:
  schedule:
    - cron: '0 6 * * *'  # Runs daily at 6 AM UTC
  workflow_dispatch:      # Allows manual triggering

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install Chrome
      run: |
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/sources.list.d/google-chrome.list'
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create service account credentials
      run: |
        echo "${{ secrets.GOOGLE_CREDENTIALS_JSON }}" > google_credentials.json
      
    - name: Run scraper
      env:
        GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
        PYTHONUNBUFFERED: 1
      run: python obituary_scraper.py
      
    - name: Upload error logs
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: error-logs
        path: error.log
