name: Run Obituary Scraper

on:
  schedule:
    - cron: '0 17 * * 4'  # Runs at 12:00 PM EST (17:00 UTC) every Thursday
  workflow_dispatch:  # Allows manual triggering

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium undetected-chromedriver beautifulsoup4 pandas python-dotenv google-oauth2-tool google-api-python-client
    
    - name: Add chrome-options
      run: |
        sudo echo '#!/bin/sh' > /usr/local/bin/chrome-options
        sudo echo 'exec "$@" --no-sandbox --headless --disable-gpu --disable-dev-shm-usage --window-size=1920,1080' >> /usr/local/bin/chrome-options
        sudo chmod +x /usr/local/bin/chrome-options
    
    - name: Print debugging info
      run: |
        echo "Chrome version:"
        google-chrome --version
        echo "Python version:"
        python --version
        echo "Working directory:"
        pwd
        echo "Directory contents:"
        ls -la
    
    - name: Run scraper
      env:
        GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
      run: |
        echo "Running scraper at $(date)"
        python -c "import json; print('Validating credentials...'); json.loads('${{ secrets.GOOGLE_CREDENTIALS_JSON }}')" || echo "Invalid JSON in credentials"
        python run_scraper.py
    
    - name: Upload log files if failure
      if: failure()
      uses: actions/upload-artifact@v4  # Updated to v4
      with:
        name: error-logs
        path: |
          *.log
          ~/obituary_scraper_logs/*.log
        retention-days: 5  # Keep logs for 5 days
