name: Run Obituary Scraper

on:
  schedule:
    - cron: '0 17 * * 4'  # Runs at 12:00 PM EST (17:00 UTC) every Thursday
  workflow_dispatch:  # Allows manual triggering

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable chromium-chromedriver
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium undetected-chromedriver beautifulsoup4 pandas python-dotenv
        pip install google-api-python-client google-auth-httplib2 google-auth-oauthlib oauth2client google-auth

    - name: Add chrome-options
      run: |
        sudo mkdir -p /usr/local/bin
        sudo echo '#!/bin/sh' > /usr/local/bin/chrome-options
        sudo echo 'exec "$@" --no-sandbox --headless --disable-gpu --disable-dev-shm-usage --window-size=1920,1080' >> /usr/local/bin/chrome-options
        sudo chmod +x /usr/local/bin/chrome-options
    
    - name: Run scraper
      env:
        GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
      run: |
        echo "Starting scraper..."
        python IntegratedObituaryPropertyScraper.py
        
    - name: Upload log files if failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: error-logs
        path: |
          *.log
          ~/obituary_scraper_logs/*.log
        retention-days: 5
